# Standards: 0.11
---

# 1.1.18 Ensure sticky bit is set on all world-writable directories

- name: 1.1.18 - List world-writable directories that do not have sticky bit set
  shell: "df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type d -perm -0002 -not -perm -1000 2>/dev/null"
  register: find_1_1_8
  always_run: yes
  changed_when: False
  tags:
    - level-1
    - section-1
    - "1.1.18"
    - scored

# not reusing find_1_1_8 result because of concerns with names containing carriage returns
- name: 1.1.8 - Add sticky bit to all world-writable directories that did not have it
  shell: "df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type d -perm -0002 -not -perm -1000 2>/dev/null -print0 | xargs -0 chmod +t"
  when: find_1_1_8.stdout_lines is defined and find_1_1_8.stdout_lines|length > 0
  tags:
    - level-1
    - section-1
    - "1.1.18"
    - scored
