# Standards: 0.11
---

# 3.1.2 Ensure packet redirect sending is disabled

- name: 3.1.2 - Ensure packet redirect sending is disabled
  sysctl:
    ignoreerrors: true
    name: "{{ item }}" 
    value: 0
    state: present
    sysctl_set: yes
  with_items:
    - "net.ipv4.conf.all.send_redirects"
    - "net.ipv4.conf.default.send_redirects"
  tags:
    - level-1
    - section-3
    - "3.1.2"
    - scored
