# Standards: 0.11
---

# 3.2.8 Ensure TCP SYN Cookies is enabled

- name: 3.2.8 - Ensure TCP SYN Cookies is enabled
  sysctl:
    ignoreerrors: yes
    name: "net.ipv4.tcp_syncookies"
    value: 1
    state: present
    sysctl_set: yes
  tags:
    - level-1
    - section-3
    - "3.2.8"
    - scored
