# Standards: 0.11
---

# 3.3.1 Ensure IPv6 router advertisements are not accepted

- name: 3.3.1 - Ensure IPv6 router advertisements are not accepted
  sysctl:
    ignoreerrors: yes
    name: "{{ item }}" 
    value: 0
    state: present
    sysctl_set: yes
  with_items:
    - "net.ipv6.conf.all.accept_ra"
    - "net.ipv6.conf.default.accept_ra"
  tags:
    - level-1
    - section-3
    - "3.3.1"
    - scored
