# Standards: 0.11
---

# 3.3.2 Ensure IPv6 redirects are not accepted

- name: 3.3.2 - Ensure IPv6 redirects are not accepted
  sysctl:
    ignoreerrors: yes
    name: "{{ item }}" 
    value: 0
    state: present
    reload: yes
  with_items:
    - "net.ipv6.conf.all.accept_redirects"
    - "net.ipv6.conf.default.accept_redirects"
  tags:
    - level-1
    - section-3
    - "3.3.2"
    - scored
