# Standards: 0.11
---

# 4.2.4 Ensure permissions on all logfiles are configured

- name: 4.2.4 - Check permissions on all logfiles
  shell: "find /var/log -type f -perm +037"
  register: check_4_2_4
  always_run: yes
  changed_when: False
  tags:
    - level-1
    - section-4
    - "4.2.4"
    - scored

# not reusing check_4_2_4 result because of concerns with names containing carriage returns
- name: 4.2.4 - Ensure permissions on all logfiles are configured
  shell: "find /var/log -type f -perm +037 -exec chmod g-wx,o-rwx {} +"
  when: check_4_2_4.stdout_lines is defined and check_4_2_4.stdout_lines|length > 0
  tags:
    - level-1
    - section-4
    - "4.2.4"
    - scored
