# Standards: 0.11
---

# 5.3.4 Ensure password hashing algorithm is SHA-512

- name: 5.3.4 - List authconfig
  shell: "authconfig --test"
  register: authconfig_1_1_8
  always_run: yes
  changed_when: False
  tags:
    - level-1
    - section-1
    - "5.3.4"
    - scored

- name: 5.3.4 - Ensure password hashing algorithm is SHA-512
  command: "authconfig --update --passalgo=sha512"
  when: '" password hashing algorithm is sha512" not in authconfig_1_1_8.stdout_lines'
  tags:
    - level-1
    - section-5
    - "5.3.4"
    - scored
